// Generated by CoffeeScript 1.6.3
(function() {
  var Webtemp;

  Webtemp = (function() {
    Webtemp.prototype.basePath = "/data";

    function Webtemp() {
      var _this = this;
      this.values = {
        tmp: '23.80',
        hum: '49.10'
      };
      this.getValues();
      this.updateView();
      $('.command').on('click', this.doApi);
      window.setInterval((function() {
        return _this.getValues();
      }), 2000);
    }

    Webtemp.prototype.getValues = function() {
      var _this = this;
      return $.getJSON("" + this.basePath + "/get", function(data) {
        _this.values = data.value;
        return _this.updateView();
      });
    };

    Webtemp.prototype.doApi = function() {
      var c;
      c = $(this).data('c');
      return $.getJSON("" + this.basePath + "/put/c/" + c);
    };

    Webtemp.prototype.updateView = function() {
      $(".tmp").html(this.values.tmp.slice(0, -1));
      return $(".hum").html(this.values.hum.slice(0, -1));
    };

    $(function() {
      return new Webtemp();
    });

    return Webtemp;

  })();

}).call(this);
